# Generated by Django 4.2.5 on 2023-10-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaGejala', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50, null=True)),
                ('jenisKelamin', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Penyakit', models.CharField(max_length=50)),
                ('gejala', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaPenyakit', models.CharField(max_length=50)),
                ('solusi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='basisPengetauan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.penyakit')),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.gejala')),
            ],
        ),
    ]
